import { RecordIds, TRecord } from '../../../../../hexagon/interfaces';

export const aRecordIds: RecordIds = {
    id: 100,
    reference: 'a145zdse58bc',
};

export const somesRecords: TRecord[] = [
    {
        id: 100,
        status: 'created',
        vehicle: {
            makeName: 'Peugeot',
            modelName: '2008',
            yearName: '2020',
            monthName: 'Enero',
            bodyName: 'Sedan',
            fuelName: 'Gasolina',
            engineName: '92CH',
            gearName: 'automatica',
            versionName: '1.6 bluehdi 75 active',
            import: true,
            mileage: 45000,
        },
        customer: {
            email: 'john@doe.fr',
            phone: '912341234',
            lastName: 'doe',
            firstName: 'john',
            zipCode: '12345',
        },
        valuation: {
            value: 10000,
            status: true,
            archived: false,
            date: new Date('2020-08-20'),
        },
        appointment: {
            status: false,
            dateHour: new Date('2020-09-20 10:00:00'),

            place: {
                sellerName: 'Juan',
                name: 'Centro de compra de Madrid',
                address: 'Calle Alcala 234',
                zipCode: '2812',
                city: 'Madrid',
                phone: '+34951345529',
                position: {
                    lat: -3.745,
                    lng: -38.523,
                },
            },
        },
    },
    {
        id: 200,
        status: 'created',
        vehicle: {
            makeName: 'Fiat',
            modelName: 'Panda',
            yearName: '2020',
            monthName: 'Enero',
            bodyName: 'Sedan',
            fuelName: 'Gasolina',
            engineName: '92CH',
            gearName: 'automatica',
            versionName: '1.6 bluehdi 75 active',
            import: true,
            mileage: 15000,
        },
        customer: {
            email: 'john@doe.fr',
            phone: '912341234',
            lastName: 'doe',
            firstName: 'john',
            zipCode: '12345',
        },
        valuation: {
            value: 6000,
            status: true,
            archived: false,
            date: new Date('2020-08-20'),
        },
        appointment: {
            status: true,
            dateHour: new Date('2020-08-20 10:00:00'),

            place: {
                sellerName: 'Juan',
                name: 'Centro de compra de Madrid',
                address: 'Calle Alcala 234',
                zipCode: '2812',
                city: 'Madrid',
                phone: '+34951345529',
                position: {
                    lat: -3.745,
                    lng: -38.523,
                },
            },
        },
    },
    {
        id: 300,
        status: 'created',
        vehicle: {
            makeName: 'Renault',
            modelName: 'Clio',
            yearName: '2020',
            monthName: 'Enero',
            bodyName: 'Sedan',
            fuelName: 'Gasolina',
            engineName: '92CH',
            gearName: 'automatica',
            versionName: '1.6 bluehdi 75 active',
            import: true,
            mileage: 20000,
        },
        customer: {
            email: 'john@doe.fr',
            phone: '912341234',
            lastName: 'doe',
            firstName: 'john',
            zipCode: '12345',
        },
        valuation: {
            value: 18000,
            status: true,
            archived: true,
            date: new Date('2020-01-01'),
        },
        appointment: {
            status: true,
            dateHour: new Date('2020-08-20 10:00:00'),
            place: {
                sellerName: 'Juan',
                name: 'Centro de compra de Madrid',
                address: 'Calle Alcala 234',
                zipCode: '2812',
                city: 'Madrid',
                phone: '+34951345529',
                position: {
                    lat: -3.745,
                    lng: -38.523,
                },
            },
        },
    },
    {
        id: 400,
        status: 'created',
        vehicle: {
            makeName: 'Peugeot',
            modelName: '2008',
            yearName: '2020',
            monthName: 'Enero',
            bodyName: 'Sedan',
            fuelName: 'Gasolina',
            engineName: '92CH',
            gearName: 'automatica',
            versionName: '1.6 bluehdi 75 active',
            import: true,
            mileage: 90000,
        },
        customer: {
            email: 'john@doe.fr',
            phone: '912341234',
            lastName: 'doe',
            firstName: 'john',
            zipCode: '12345',
        },
        valuation: {
            value: 0,
            status: false,
            archived: false,
            date: new Date('2020-08-20'),
        },
        appointment: {
            status: false,
            dateHour: new Date('2020-08-20 10:00:00'),
            place: {
                sellerName: 'Juan',
                name: 'Centro de compra de Madrid',
                address: 'Calle Alcala 234',
                zipCode: '2812',
                city: 'Madrid',
                phone: '+34951345529',
                position: {
                    lat: -3.745,
                    lng: -38.523,
                },
            },
        },
    },
];
