import { RecordIds, TRecord } from '../../../../../hexagon/interfaces';

export const aRecordIds: RecordIds = {
    id: 100,
    reference: 'a145zdse58bc',
};

export const somesRecords: TRecord[] = [
    {
        id: '100',
        expired: false,
        offerNumber: 'WITHOUT_APPOINTMENT',
        vehicle: {
            makeName: 'Peugeot',
            modelName: '2008',
            yearName: '2020',
            monthName: 'Enero',
            bodyName: 'Sedan',
            fuelName: 'Gasolina',
            engineName: '92CH',
            gearName: 'automatica',
            versionName: '1.6 bluehdi 75 active',
            import: true,
            mileage: 45000,
            doors: '5',
        },
        customer: {
            email: 'john@doe.fr',
            phone: '912341234',
            lastName: 'doe',
            firstName: 'john',
            zipCode: '12345',
        },
        // valuation: {
        //     value: 10000,
        //     status: true,
        //     archived: false,
        //     date: new Date('2020-08-20'),
        // },
    },
    {
        id: '200',
        expired: false,
        offerNumber: 'WITH_APPOINTMENT',
        vehicle: {
            makeName: 'Fiat',
            modelName: 'Panda',
            yearName: '2020',
            monthName: 'Enero',
            bodyName: 'Sedan',
            fuelName: 'Gasolina',
            engineName: '92CH',
            gearName: 'automatica',
            versionName: '1.6 bluehdi 75 active',
            import: true,
            mileage: 15000,
            doors: '5',
        },
        customer: {
            email: 'john@doe.fr',
            phone: '912341234',
            lastName: 'doe',
            firstName: 'john',
            zipCode: '12345',
        },
        valuation: {
            value: 6000,
            status: true,
            archived: false,
            date: new Date('2020-08-20'),
        },
        appointment: {
            status: true,
            dateHour: '2020-08-20 10:00:00',

            place: {
                sellerName: 'Juan',
                name: 'Centro de compra de Madrid',
                address: 'Calle Alcala 234',
                zipCode: '2812',
                city: 'Madrid',
                phone: '+34951345529',
                position: {
                    lat: -3.745,
                    lng: -38.523,
                },
            },
        },
    },
    {
        id: '300',
        expired: true,
        offerNumber: 'EXPIRED',
        vehicle: {
            makeName: 'Renault',
            modelName: 'Clio',
            yearName: '2020',
            monthName: 'Enero',
            bodyName: 'Sedan',
            fuelName: 'Gasolina',
            engineName: '92CH',
            gearName: 'automatica',
            versionName: '1.6 bluehdi 75 active',
            import: true,
            mileage: 20000,
            doors: '5',
        },
        customer: {
            email: 'john@doe.fr',
            phone: '912341234',
            lastName: 'doe',
            firstName: 'john',
            zipCode: '12345',
        },
        valuation: {
            value: 18000,
            status: true,
            archived: true,
            date: new Date('2020-01-01'),
        },
    },
    {
        id: '500',
        expired: false,
        offerNumber: 'NOT_QUOTABLE',
        vehicle: {
            makeName: 'Peugeot',
            modelName: '2008',
            yearName: '2020',
            monthName: 'Enero',
            bodyName: 'Sedan',
            fuelName: 'Gasolina',
            engineName: '92CH',
            gearName: 'automatica',
            versionName: '1.6 bluehdi 75 active',
            import: true,
            mileage: 90000,
            doors: '5',
        },
        customer: {
            email: 'john@doe.fr',
            phone: '912341234',
            lastName: 'doe',
            firstName: 'john',
            zipCode: '12345',
        },
    },
    {
        id: '400',
        expired: false,
        offerNumber: 'REFRESHED',
        vehicle: {
            makeName: 'Peugeot',
            modelName: '2008',
            yearName: '2020',
            monthName: 'Enero',
            bodyName: 'Sedan',
            fuelName: 'Gasolina',
            engineName: '92CH',
            gearName: 'automatica',
            versionName: '1.6 bluehdi 75 active',
            import: true,
            mileage: 90000,
            doors: '5',
        },
        customer: {
            email: 'john@doe.fr',
            phone: '912341234',
            lastName: 'doe',
            firstName: 'john',
            zipCode: '12345',
        },
        valuation: {
            value: 17500,
            status: false,
            archived: false,
            date: new Date('2020-08-20'),
        },
    },
];
